/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AlloraAdapterBringPredictionOnChainExample } from "./AlloraAdapterBringPredictionOnChainExample";
export type { UpshotAdapterBringPredictionOnChainExample } from "./UpshotAdapterBringPredictionOnChainExample";
