/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUpshotAdapter,
  IUpshotAdapterInterface,
} from "../IUpshotAdapter";

const _abi = [
  {
    type: "function",
    name: "getTopic",
    inputs: [
      {
        name: "topicId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "topicView",
        type: "tuple",
        internalType: "struct TopicView",
        components: [
          {
            name: "config",
            type: "tuple",
            internalType: "struct TopicConfig",
            components: [
              {
                name: "title",
                type: "string",
                internalType: "string",
              },
              {
                name: "owner",
                type: "address",
                internalType: "address",
              },
              {
                name: "dataProviderQuorum",
                type: "uint48",
                internalType: "uint48",
              },
              {
                name: "dataValiditySeconds",
                type: "uint48",
                internalType: "uint48",
              },
              {
                name: "aggregator",
                type: "address",
                internalType: "contract IAggregator",
              },
              {
                name: "ownerSwitchedOn",
                type: "bool",
                internalType: "bool",
              },
              {
                name: "adminSwitchedOn",
                type: "bool",
                internalType: "bool",
              },
            ],
          },
          {
            name: "validDataProviders",
            type: "address[]",
            internalType: "address[]",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTopicValue",
    inputs: [
      {
        name: "topicId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "extraData",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct TopicValue",
        components: [
          {
            name: "recentValue",
            type: "uint192",
            internalType: "uint192",
          },
          {
            name: "recentValueTime",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "verifyData",
    inputs: [
      {
        name: "pd",
        type: "tuple",
        internalType: "struct UpshotAdapterNumericData",
        components: [
          {
            name: "signedNumericData",
            type: "tuple[]",
            internalType: "struct SignedNumericData[]",
            components: [
              {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "numericData",
                type: "tuple",
                internalType: "struct NumericData",
                components: [
                  {
                    name: "topicId",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "timestamp",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "numericValue",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "extraData",
                    type: "bytes",
                    internalType: "bytes",
                  },
                ],
              },
            ],
          },
          {
            name: "extraData",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "numericValue",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "verifyDataViewOnly",
    inputs: [
      {
        name: "pd",
        type: "tuple",
        internalType: "struct UpshotAdapterNumericData",
        components: [
          {
            name: "signedNumericData",
            type: "tuple[]",
            internalType: "struct SignedNumericData[]",
            components: [
              {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "numericData",
                type: "tuple",
                internalType: "struct NumericData",
                components: [
                  {
                    name: "topicId",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "timestamp",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "numericValue",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "extraData",
                    type: "bytes",
                    internalType: "bytes",
                  },
                ],
              },
            ],
          },
          {
            name: "extraData",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "numericValue",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IUpshotAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): IUpshotAdapterInterface {
    return new Interface(_abi) as IUpshotAdapterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUpshotAdapter {
    return new Contract(address, _abi, runner) as unknown as IUpshotAdapter;
  }
}
